# Generated by Django 4.1 on 2023-11-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("UserModel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="loseORadd",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="target",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
