# Generated by Django 4.2.4 on 2023-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserModel', '0002_alter_user_age_alter_user_gender_alter_user_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=100)),
                ('video_title', models.CharField(max_length=100)),
            ],
        ),
    ]
